SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET XACT_ABORT ON  

USE [$(dbUniHangouts)]
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_Event_RSVP_AddOrUpdate]
   @EventID BIGINT,
   @AccountID BIGINT,
   @RSVPTypeID SMALLINT
AS
SET NOCOUNT ON;


BEGIN TRANSACTION;
BEGIN TRY 

   IF EXISTS (SELECT TOP 1 * FROM [dbo].EventRSVPs WHERE EventID = @EventID AND AccountID = @AccountID)
      BEGIN
         UPDATE dbo.EventRSVPs SET RSVPTypeId = @RSVPTypeID WHERE EventID = @EventID AND AccountID = @AccountID
      END 
   ELSE 
      BEGIN
         INSERT INTO dbo.EventRSVPs(EventID, AccountID, RSVPTypeId) VALUES (@EventID, @AccountID, @RSVPTypeID);
      END

   COMMIT TRANSACTION;
END TRY  
BEGIN CATCH  
   ROLLBACK TRANSACTION;  
   THROW;
END CATCH 



GO
