SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET XACT_ABORT ON  

USE [$(dbUniHangouts)]
GO
CREATE OR ALTER PROCEDURE [dbo].[sp_Event_TagAdd]
   @EventID BIGINT,
   @TagID BIGINT
AS
SET NOCOUNT ON;


INSERT INTO dbo.EventTagMap(EventID, TagID) VALUES (@EventID, @TagID);


GO
